### ISSUE TITLE
Thoughts on traits selection in ValidateSetPropertiesByPath() and SetPropertiesByPath()

### ISSUE THREAD

**Issue by Pete-Cordell** [AMWA-TV/is-device-configuration#14]
I suggest renaming includedPropertyTraits to propertyTraitsFilter and make it nullable (i.e. sequence&lt;NcPropertyTrait>? propertyTraitsFilter).

Then describing propertyTraitsFilter as:

propertyTraitsFilter - If non-null, specifies that only role paths with the traits specified by this property are to be validated / restored.  If the parameter is null, the operation should proceed as if this property was set to "General", "Structural", "InstanceSpecific", and "DeviceGenerated" thus invoking a full restore.

**Comment by cristian-recoseanu** [comment]
We have since removed the concept of traits and made it the responsibility of a client to manipulate the backup data set for any intended use.
