### ISSUE TITLE
Review that set of traits is sufficient

### ISSUE THREAD

**Issue by Pete-Cordell** [AMWA-TV/is-device-configuration#17]
I'm keen to check that the list of traits is flexible enough to deal with the various restore scenarios we might encounter.  To explore that, here's a list of property types from one of our config files that we should assign traits to.  If multiple types of data have the same trait, are there scenarios where we would want to restore some of the properties with that trait but not all of them?  If so, do we need additional traits?

- User supplied device name

- User supplied asset number

- serial number

- software build information

- Active license file

- timezone

- SNMP settings including addresses

- Alarms

- List of included cards

- Ethernet interface settings

  - MAC addresses, num tx-packets, num rx-packets, speeds

- Stream data such as ip addresses, FEC

- User supplied stream label

- Streams statistics - last hour, last day, last week etc.

- SFP info

- Management IP interface (separate to media IP interfaces - DHCP? / Default gateway? etc)

- BCP-002-02 type information

- IS-13 type information

- IS-05 codec type values

- IS-05 network address type values

- IS-05 activation times?

- IS-08 audio mapping values

- IS-04 UUID values

- NcBlock type information (lists of other objects)

**Comment by Pete-Cordell** [comment]
Pete Brightwell's display of NMOS specs according to theme suggests another way to check that our traits are sufficient.  I see the themes below as being attractive from a partial backup and restore point of view.  Note that some parts of a theme can be unique to a device whereas as some parts can be common across multiple devices.  Where it looks like a theme has both parts I've separated them out into two parts below:

- IS-04/09/08/05/07{codecs/fec/sips settings} -> device structure

- IS-04 UUIDs -> entity identifiers

- BCP-002-02 (e.g. vendor, serial numbers) -> device identity

- IS-13 (user identifiers)

- IS-05/07{network addresses} -> connectivity

- IS-10 (e.g. certificates/passwords etc) -> security

- BCP-008-02 and similar (statistics and alarms/SNMP etc) -> monitoring

**Comment by cristian-recoseanu** [comment]
We have since removed the concept of traits and made it the responsibility of a client to manipulate the backup data set for any intended use.
