### ISSUE TITLE
Thoughts on possible alternative traits

### ISSUE THREAD

**Issue by Pete-Cordell** [AMWA-TV/is-device-configuration#18]
If our current use of traits doesn’t hit the spot, maybe we can consider this approach…

If I image a rack of devices all doing the same function (e.g. SDI to 2110-???), in terms of configuration there is some settings that all units will have (e.g. codec type), some that is specific to the device (e.g. device name, serial number) and some that is specific to the streams that are being sent/received (e.g. IP addresses, lost packet accounts, certain tags).  That suggests to me that there are three categories of information: Common settings (let’s call them `General`), Device Specific (let’s call them `Device`) and Stream specific (let’s call them `Stream`).

Then there is stuff that a controller can change and that which a controller can’t change.  Let’s call these `Writable` and `Read-Only`.

Combining these, we get categories of `Device Writable`(e.g. device name), `Device Read-Only ` (e.g. serial number), `General Writable` (e.g. SIPS/FEC settings) , `General Read-Only`(e.g. IS-04 UUID?), `Stream Writable` (e.g. IP addresses) and `Stream Read-Only`(e.g. lost packet counts).

A Backup Data Set would include properties with all six categories, but when restoring a Data Set a user would specify one or more of `Device`, `General`, `Stream`.  Properties with a Read-Only category would be ignored when restoring and no warning would be generated.

A full kit replacement restore would select all three categories.

A kit parking or change of program would likely only select `Stream`.

A mass-provisioning via cloning would initially just select `General`(or possibly also `Stream` with some default values).

Jeff’s suggestion of rebuilds vs. restores plays in well to this.  To make it easier for me, building on the terminology of C++ compilers, how do people feel about calling these a `clean restore` and an `incremental restore`?  These could be flagged as part of the restore operation.  (A mass-provisioning could do a `clean restore` with just the `General` properties so wouldn’t technically be a rebuild.)

**Comment by cristian-recoseanu** [comment]
We have since removed the concept of traits and made it the responsibility of a client to manipulate the backup data set for any intended use.
