### ISSUE TITLE
Backup Dataset RolePaths - relative or absolute?

### ISSUE THREAD

**Issue by jonathan-r-thorpe** [AMWA-TV/is-device-configuration#19]
In the backup dataset are the role paths relative or explicit? 

Explicit:
- You always know to which part of the Device Model the backup dataset relates
- It doesn't matter what the target of the backup dataset it as you can apply the backup dataset to any role path.

Relative:
- The backup dataset can be applied more flexibly
- The target of the backup dataset matters, as each role path is relative to the target.

My assumption is that the role paths would be relative but either way this needs to be stated in the specification to avoid confusion.

**Comment by cristian-recoseanu** [comment]
I think the role path in a `NcObjectPropertiesHolder` has to be absolute as it is expressed in the `NcBulkValuesHolder` as a flat collection in the values field.

```typescript
interface NcBulkValuesHolder {
    attribute NcString?    validationFingerprint; // Optional vendor specific fingerprinting mechanism used for validation purposes
    attribute sequence<NcObjectPropertiesHolder>    values; // Values by rolePath
};
```

This also matches the response from the `/rolePaths` endpoint which returns absolute paths.

I agree we should explicitly mention in the specs that this is the case.

**Comment by jonathan-r-thorpe** [comment]
Great. Also it would be worth noting in the specification that the absolute paths means you can apply the backup to any of the role path endpoints.  

However, perhaps worth recommending to apply it to `rolePaths/root/bulkProperties` ?
