### ISSUE TITLE
MS-05 Constraints Violations

### ISSUE THREAD

**Issue by jonathan-r-thorpe** [AMWA-TV/is-device-configuration#20]
Does the backup mechanism obey the constraints MS-05 mechanism? i.e. if the client attempts to configure a property to a value that violates constraints, should it cause an error?

If the client attempts to configure a value to one that violates constraints, should there be a specific error code? Or should that be in the error message?

How does the client know what the constraints for a configurable value are? Should the constraints be included in the backup dataset?

**Comment by cristian-recoseanu** [comment]
The constraints are already available in the data model and can be accessed via the `/descriptor` endpoints for:
* a rolePath (class descriptor)
* a property (datatype descriptor)

These are already in the backup data set as part of the class manager branch.
