### ISSUE TITLE
Data type marshalling: correct handling of 64 bit integers

### ISSUE THREAD

**Issue by jonathan-r-thorpe** [AMWA-TV/is-device-configuration#5]
https://github.com/AMWA-TV/is-14/blob/publish-CR/docs/Data%20type%20marshalling.md

JSON currently only supports integers with a maximum of 53 bits, and so handling of 64-bit integers needs to either be transmitted as text or split into two 32-bit integers and recombined.

This specification, and for that matter [IS-12](https://specs.amwa.tv/is-12/branches/v1.0.x/docs/Data_type_marshalling.html), needs to determine which work around is to be used.

**Comment by cristian-recoseanu** [comment]
I am not sure this is a limitation of the JSON spec but rather a limitation of the Javascript parsers.

https://lwn.net/Articles/730671/

https://stackoverflow.com/questions/209869/what-is-the-accepted-way-to-send-64-bit-values-over-json

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt

**Comment by cristian-recoseanu** [comment]
This has since been addressed for Javascript by using the BigInt type.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt
